### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by mikedwtmp** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-mikedwtmp#1]
![019F02B2-CF22-4CE9-B717-A714E7BC8BA5](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-mikedwtmp/assets/121983831/8b951ecd-8d66-4fe5-a615-b82529ff83a1)

**Comment by instructorc** [comment]
Deliverable met
