### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by mikedwtmp** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-mikedwtmp#2]
![66B9AE47-C7DF-4325-9EC5-00AABCE6C462](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-mikedwtmp/assets/121983831/bdb6de40-f8e0-4201-a40d-10303fe7e955)

**Comment by instructorc** [comment]
Deliverable met!
